/* DO NOT EDIT THIS FILE - it is machine generated */
#include <native.h>
/* Header for class HelloWorld */

#ifndef _Included_HelloWorld
#define _Included_HelloWorld

#pragma pack(4)

typedef struct ClassHelloWorld {
    long MyNumber;
} ClassHelloWorld;
HandleTo(HelloWorld);

#pragma pack()

#ifdef __cplusplus
extern "C" {
#endif
extern void HelloWorld_displayHelloWorld(struct HHelloWorld *);
#ifdef __cplusplus
}
#endif
#endif
