#!/bin/ksh 

JBOSSHOME=~/jboss

CLASSPATH=.:..

for thing in ${JBOSSHOME}/client/*
do
    if [ -f $thing ]; then
        CLASSPATH="$CLASSPATH:$thing"
    elif [ -d $thing ]; then
        CLASSPATH="$CLASSPATH:$thing"
    fi
done

set -x

java -classpath build:$CLASSPATH CartClient
