#!/bin/ksh -u

# compile everyting in the javasrc directory to ensure that it's
# all still compilable :-) and to see what deprecation warning remain.
#
# There may always be a few due to Date() and PrintStream().

javac -deprecation *.java

let numExpected="$(grep 'EXPECT COMPILE ERROR' *.java | wc -l)"
echo "Of those errors, $numExpected were expected!"
