#!/usr/bin/awk -f

BEGIN {
	print "== Index By Chapter"
	print "This is the index of files included in the Java Cookbook 4th Edition."
	print ""
}

/^== / {
	sub(/^== /, "", $0)
	print ".", $0
}
/^include::src/ {
	sub(/^include::/, "* link:", $0)
	print $0
}
/^\/\/ [A-Za-z0-9\/]+\.java/ {
	print "* link:src/main/java/" $2 "[]"
}
