# Makefile.simple -- simple makefile to build all Java classes.
# Remember to "make makefiles.clean" before editing this file!
# $Id$

JAVACC?=	jikes +E

all:	classes

classes:
		@echo "===> Building in `pwd`"
		$(JAVACC) *.java
