= JavaCook Source Files (javasrc)

Many but by no means all of these files are used in my 
https://javacook.darwinsys.com/[Java Cookbook].
I use a script to pre-format these for inclusion in the O'Reilly publishing toolchain;
these will have "// BEGIN" and "// END" comments to mark sections for
mechanical inclusion into the book. These are just comments to Java tooling and can be
completely ignored by people looking at the source code normally.
Not all files with these comments necessarily appear in the book.

== Building

* You MUST HAVE Java 9+ to successfully compile this whole package.  Sorry
if you are on some relic platform that doesn't have Java 9 or later.
Even OpenBSD has Java 11 (Thanks Kurt!).
Also sorry if your organization is stuck on Java 7 or 8 due to application server issues.
I am updating the Java Cookbook for Java 12 and these files are the examples for
that book.

* I am using Eclipse for most of my development, and Maven for building, and Jenkins
for automated building. Most Ant scripts have been removed; the few that remain
will eventually be converted to Maven exec:java configurations.

* Building with Eclipse tested with Eclipse 4.3; MUST HAVE "m2e" (free in the Eclipse Marketplace)
	Compiles and tests pass.

* Building with Maven 3.x works and tests pass.

* Building with other platforms? Good luck, but let me know if it works.

. If you really need Java 8, try removing the module-info file. But you're on your own.

Ian Darwin

Java Cookbook author

http://www.darwinsys.com/contact.jsp

