package strings;

/* AllTests - generated by Ian Darwin's alltest script */

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(value=Suite.class)
@SuiteClasses(value={
	DeTabTest.class,
	EnTabTest.class,
	FmtTest.class,
	SoundexTest.class,
	StringAlignTest.class,
	TabsTest.class,
	UndentTest.class
})
public class AllTests {
	// No Code Needed
}

