

/**
 * JModem - simple communications program.
 * @author    Ian F. Darwin, ian@darwinsys.com
 * @version   $Id$
 */
public class JModem extends javax.swing.JFrame {

  /** Initializes the Form */
  public JModem() {
    initComponents ();
    pack ();
  }

  /** This method is called from within the constructor to
   * initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is
   * always regenerated by the FormEditor.
   */
  private void initComponents () {//GEN-BEGIN:initComponents
    addWindowListener (new java.awt.event.WindowAdapter () {
        public void windowClosing (java.awt.event.WindowEvent evt) {
          exitForm (evt);
        }
      }
    );
    getContentPane ().setLayout (new java.awt.BorderLayout ());

    connectPanel = new javax.swing.JPanel ();
    connectPanel.setLayout (new java.awt.FlowLayout ());

      jLabel1 = new javax.swing.JLabel ();
      jLabel1.setText ("Connection");
      connectPanel.add (jLabel1);

      jLabel2 = new javax.swing.JLabel ();
      jLabel2.setText ("Speed");
      connectPanel.add (jLabel2);

      jComboBox2 = new javax.swing.JComboBox ();
      connectPanel.add (jComboBox2);

      jPanel3 = new javax.swing.JPanel ();
      jPanel3.setPreferredSize (new java.awt.Dimension(50, 50));
      jPanel3.setMinimumSize (new java.awt.Dimension(0, 0));
      jPanel3.setLayout (new javax.swing.BoxLayout (jPanel3, 1));

        jRadioButton1 = new javax.swing.JRadioButton ();
        jRadioButton1.setText ("7");
        jPanel3.add (jRadioButton1);

        jRadioButton2 = new javax.swing.JRadioButton ();
        jRadioButton2.setText ("8");
        jPanel3.add (jRadioButton2);

      connectPanel.add (jPanel3);

      jPanel4 = new javax.swing.JPanel ();
      jPanel4.setPreferredSize (new java.awt.Dimension(50, 50));
      jPanel4.setLayout (new javax.swing.BoxLayout (jPanel4, 1));

        jRadioButton3 = new javax.swing.JRadioButton ();
        jRadioButton3.setText ("Even");
        jPanel4.add (jRadioButton3);

        jRadioButton4 = new javax.swing.JRadioButton ();
        jRadioButton4.setText ("Odd");
        jPanel4.add (jRadioButton4);

        jRadioButton5 = new javax.swing.JRadioButton ();
        jRadioButton5.setText ("None");
        jPanel4.add (jRadioButton5);

      connectPanel.add (jPanel4);

      jComboBox3 = new javax.swing.JComboBox ();
      connectPanel.add (jComboBox3);

      connectButton = new javax.swing.JButton ();
      connectButton.setText ("Connect");
      connectButton.addActionListener (new java.awt.event.ActionListener () {
          public void actionPerformed (java.awt.event.ActionEvent evt) {
            connectButtonActionPerformed (evt);
          }
        }
      );
      connectPanel.add (connectButton);

    getContentPane ().add (connectPanel, "North");

    xferPanel = new javax.swing.JPanel ();
    xferPanel.setLayout (new java.awt.FlowLayout ());

      jLabel3 = new javax.swing.JLabel ();
      jLabel3.setText ("Transfer");
      xferPanel.add (jLabel3);

      jPanel6 = new javax.swing.JPanel ();
      jPanel6.setLayout (new javax.swing.BoxLayout (jPanel6, 1));

        jRadioButton6 = new javax.swing.JRadioButton ();
        jRadioButton6.setText ("Send");
        jPanel6.add (jRadioButton6);

        jRadioButton7 = new javax.swing.JRadioButton ();
        jRadioButton7.setText ("Receive");
        jPanel6.add (jRadioButton7);

      xferPanel.add (jPanel6);

      jLabel4 = new javax.swing.JLabel ();
      jLabel4.setText ("Filename:");
      xferPanel.add (jLabel4);

      jTextField1 = new javax.swing.JTextField ();
      jTextField1.setPreferredSize (new java.awt.Dimension(100, 20));
      xferPanel.add (jTextField1);

      jPanel7 = new javax.swing.JPanel ();
      jPanel7.setLayout (new javax.swing.BoxLayout (jPanel7, 1));

        jRadioButton8 = new javax.swing.JRadioButton ();
        jRadioButton8.setText ("Text");
        jPanel7.add (jRadioButton8);

        jRadioButton9 = new javax.swing.JRadioButton ();
        jRadioButton9.setText ("Binary");
        jPanel7.add (jRadioButton9);

      xferPanel.add (jPanel7);

      xferButton = new javax.swing.JButton ();
      xferButton.setText ("Transfer");
      xferButton.addActionListener (new java.awt.event.ActionListener () {
          public void actionPerformed (java.awt.event.ActionEvent evt) {
            xferButtonActionPerformed (evt);
          }
        }
      );
      xferPanel.add (xferButton);

    getContentPane ().add (xferPanel, "South");

    theTextArea = new javax.swing.JTextArea ();
    getContentPane ().add (theTextArea, "Center");

  }//GEN-END:initComponents

  private void xferButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xferButtonActionPerformed
    // Do the transfer, using TModem class.
  }//GEN-LAST:event_xferButtonActionPerformed

  private void connectButtonActionPerformed (java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButtonActionPerformed
    // Open the specified serial port
  }//GEN-LAST:event_connectButtonActionPerformed


  /** Exit the Application */
  private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
    System.exit (0);
  }//GEN-LAST:event_exitForm


// Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel connectPanel;
  private javax.swing.JPanel xferPanel;
  private javax.swing.JTextArea theTextArea;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JComboBox jComboBox2;
  private javax.swing.JPanel jPanel3;
  private javax.swing.JRadioButton jRadioButton1;
  private javax.swing.JRadioButton jRadioButton2;
  private javax.swing.JPanel jPanel4;
  private javax.swing.JRadioButton jRadioButton3;
  private javax.swing.JRadioButton jRadioButton4;
  private javax.swing.JRadioButton jRadioButton5;
  private javax.swing.JComboBox jComboBox3;
  private javax.swing.JButton connectButton;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JPanel jPanel6;
  private javax.swing.JRadioButton jRadioButton6;
  private javax.swing.JRadioButton jRadioButton7;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JTextField jTextField1;
  private javax.swing.JPanel jPanel7;
  private javax.swing.JRadioButton jRadioButton8;
  private javax.swing.JRadioButton jRadioButton9;
  private javax.swing.JButton xferButton;
// End of variables declaration//GEN-END:variables


  public static void main(java.lang.String[] args) {
    new JModem ().show ();
  }

}
