/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DBM */

#ifndef _Included_DBM
#define _Included_DBM
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: inuse */
/*
 * Class:     DBM
 * Method:    dbminit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_DBM_dbminit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     DBM
 * Method:    dbmclose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DBM_dbmclose
  (JNIEnv *, jobject);

/*
 * Class:     DBM
 * Method:    dbmfetch
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_DBM_dbmfetch
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     DBM
 * Method:    dbmstore
 * Signature: ([B[B)I
 */
JNIEXPORT jint JNICALL Java_DBM_dbmstore
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

/*
 * Class:     DBM
 * Method:    delete
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_DBM_delete
  (JNIEnv *, jobject, jobject);

/*
 * Class:     DBM
 * Method:    firstkey
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_DBM_firstkey
  (JNIEnv *, jobject);

/*
 * Class:     DBM
 * Method:    nextkey
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_DBM_nextkey
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
