/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class DBM */

#ifndef _Included_DBM
#define _Included_DBM
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: inuse */
/*
 * Class:     DBM
 * Method:    dbmclose
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_DBM_dbmclose
  (JNIEnv *, jobject);

/*
 * Class:     DBM
 * Method:    dbminit
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_DBM_dbminit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     DBM
 * Method:    delete
 * Signature: (Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_DBM_delete
  (JNIEnv *, jobject, jobject);

/*
 * Class:     DBM
 * Method:    fetch
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_DBM_fetch
  (JNIEnv *, jobject, jobject);

/*
 * Class:     DBM
 * Method:    firstkey
 * Signature: ()Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_DBM_firstkey
  (JNIEnv *, jobject);

/*
 * Class:     DBM
 * Method:    nextkey
 * Signature: (Ljava/lang/Object;)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_DBM_nextkey
  (JNIEnv *, jobject, jobject);

/*
 * Class:     DBM
 * Method:    store
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_DBM_store
  (JNIEnv *, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
