import java.awt.*;
import java.sql.*;

/** A database MetaData query
 * @version $Id$
 */
public class JDBCMeta {

	public static void main(String av[]) {
		int i;
	    try {
			System.out.println("Loading Driver (with Class.forName)");
			// Load the jdbc-odbc bridge driver
			Class.forName ("sun.jdbc.odbc.JdbcOdbcDriver");

			System.out.println("Getting Connection");
			Connection con = DriverManager.getConnection (
				"jdbc:odbc:FedexShip - AddressBook1",
				"ian", "");	// user, passwd

			// Any warnings generated by the connect?
			checkForWarning(con.getWarnings());

			System.out.println("Getting MetaData");
			DatabaseMetaData meta = con.getMetaData();

			ResultSet res;
			System.out.println("Listing Catalogs");
			res = meta.getCatalogs();
			i = 0;
			while (res.next()) {
				System.out.println("Row " + ++i);
				System.out.println(res.getString(1));
			}
			res.close();

			// Try to list all possible columns
			System.out.println("Listing Columns");
			res = meta.getColumns(null, "", "*", "*");
			i = 0;
			while (res.next()) {
				System.out.println("Row " + ++i);
				System.out.println(res.getString(4));
			}
			res.close();

			// Try to list all possible tables
			System.out.println("Listing Tables");
			res = meta.getTables(null, "", "*", null);
			i = 0;
			while (res.next()) {
				System.out.println("Row " + ++i);
				System.out.println(res.getString(1));
			}
			res.close();

			con.close();

			System.out.println("All done!");

	    } catch (ClassNotFoundException e) {
			System.out.println("Can't load driver " + e);
	    } catch (SQLException ex) {
			System.out.println("Database access failed:");
			System.out.println(ex);
	    }
	}

	// Format and print any warnings from the connection
	private static boolean checkForWarning (SQLWarning warn) throws SQLException  {
             boolean rc = false;

             // If a SQLWarning object was given, display the
             // warning messages.  Note that there could be
             // multiple warnings chained together

             if (warn != null) {
                     System.out.println("*** Warning ***\n");
                     rc = true;
                     while (warn != null) {
                             System.out.println("SQLState: " +
                                     warn.getSQLState ());
                             System.out.println("Message:  " +
                                     warn.getMessage ());
                             System.out.println("Vendor:   " +
                                     warn.getErrorCode ());
                             System.out.println("");
                             warn = warn.getNextWarning ();
                     }
             }
             return rc;
     }
}
