#!/bin/sh

cd /home/ian/javasrc/jdbc

# Since Drivers almost always come in a Jar file, put its name here...
DRIVER_JAR=lib/hsqldb.jar
#DRIVER_JAR=lib/postgresql.jar

set -x

java -classpath .:${DRIVER_JAR} SQLRunner $*
