#!/bin/sh

cd /home/ian/javasrc/jdbc

# Since Drivers almost always come in a Jar file, put its name here...
DRIVER_JARS=lib/hsqldb.jar:lib/postgresql.jar

set -x

java -classpath .:${DRIVER_JARS} SQLRunner $*
