package strings;

/** Print "upside down" text, as generated by converters at
 * http://www.revfad.com/flip.html and at
 * http://www.fileformat.info/convert/text/upside-down.htm
 */
public class UnicodeUpsideDown {
	public static void main(String[] args) {
		System.out.println("Ian Darwin -> uıʍɹɐ◖ uɐI");
	}
}
