package structure;

/* AllTests - generated by Ian Darwin's alltest script */

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(value=Suite.class)
@SuiteClasses(value={
	// CallTrackTest.class,
	LinkListTest.class,
	ListFormatTest.class,
	ListInterchangeTest.class,
	MyMapTest.class,
	MyStackTest.class,
	QueueTest.class,
	RandomPropsTest.class,
	ToyStackTest.class
})
public class AllTests {
	// No Code Needed
}

