package io;

/* AllTests - generated by Ian Darwin's alltest script */

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(value=Suite.class)
@SuiteClasses(value={
	EscapeContLineReaderTest.class,
	FortranLineReaderTest.class,
	IndentContLineReaderTest.class,
	SimpleCalcTest.class
})
public class AllTests {
	// No Code Needed
}

