#!/bin/sh

# mkindex - runs MkIndex from its source but indexing all in target.
# overwrites index-byname in target.

TARGET=..

set -x

export CLASSPATH="`pwd`:$CLASSPATH"

cd ${TARGET}

java MkIndex *
