/* The CD Lookup */
module CDService {
	struct CD {
		long cdNumber;
		string title;
	};

	struct Track {
		string title;
		short runSeconds;
	};

	interface CDList {
		CD getCD(in long cdNum);
		Track  nextTrack();
	};
};
