/* The CD Lookup Service */
module CDService {
	struct Track {
		string title;
		long runSeconds;
	};

	typedef sequence <Track> Tracks;

	interface CD {
		attribute string title;
		Tracks  getTracks();
	};

	interface CDListIterator {
		void first();
		boolean hasNext();
		CD next();
	};
};
