package numbers;

/* AllTests - generated by Ian Darwin's alltest script */

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

@RunWith(value=Suite.class)
@SuiteClasses(value={
	BigNumCalcTest.class,
	ComplexTest.class,
	FibonacciTest.class,
	GetNumberTest.class,
	RomanNumberFormatTest.class
})
public class AllTests {
	// No Code Needed
}

