/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_darwinsys_signal_LibSignal */

#ifndef _Included_com_darwinsys_signal_LibSignal
#define _Included_com_darwinsys_signal_LibSignal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_darwinsys_signal_LibSignal
 * Method:    setsighandler
 * Signature: (Ljava/lang/Thread;)V
 */
JNIEXPORT void JNICALL Java_com_darwinsys_signal_LibSignal_setsighandler
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
