/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class BSDSerialPort */

#ifndef _Included_BSDSerialPort
#define _Included_BSDSerialPort
#ifdef __cplusplus
extern "C" {
#endif
#undef BSDSerialPort_DATABITS_5
#define BSDSerialPort_DATABITS_5 5L
#undef BSDSerialPort_DATABITS_6
#define BSDSerialPort_DATABITS_6 6L
#undef BSDSerialPort_DATABITS_7
#define BSDSerialPort_DATABITS_7 7L
#undef BSDSerialPort_DATABITS_8
#define BSDSerialPort_DATABITS_8 8L
#undef BSDSerialPort_STOPBITS_1
#define BSDSerialPort_STOPBITS_1 1L
#undef BSDSerialPort_STOPBITS_2
#define BSDSerialPort_STOPBITS_2 2L
#undef BSDSerialPort_STOPBITS_1_5
#define BSDSerialPort_STOPBITS_1_5 3L
#undef BSDSerialPort_PARITY_NONE
#define BSDSerialPort_PARITY_NONE 0L
#undef BSDSerialPort_PARITY_ODD
#define BSDSerialPort_PARITY_ODD 1L
#undef BSDSerialPort_PARITY_EVEN
#define BSDSerialPort_PARITY_EVEN 2L
#undef BSDSerialPort_PARITY_MARK
#define BSDSerialPort_PARITY_MARK 3L
#undef BSDSerialPort_PARITY_SPACE
#define BSDSerialPort_PARITY_SPACE 4L
#undef BSDSerialPort_FLOWCTRL_NONE
#define BSDSerialPort_FLOWCTRL_NONE 0L
#undef BSDSerialPort_FLOWCTRL_RTSCTS_IN
#define BSDSerialPort_FLOWCTRL_RTSCTS_IN 1L
#undef BSDSerialPort_FLOWCTRL_RTSCTS_OUT
#define BSDSerialPort_FLOWCTRL_RTSCTS_OUT 2L
#undef BSDSerialPort_FLOWCTRL_XONXOFF_IN
#define BSDSerialPort_FLOWCTRL_XONXOFF_IN 4L
#undef BSDSerialPort_FLOWCTRL_XONXOFF_OUT
#define BSDSerialPort_FLOWCTRL_XONXOFF_OUT 8L
/*
 * Class:     BSDSerialPort
 * Method:    bsdstty
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_BSDSerialPort_bsdstty
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     BSDSerialPort
 * Method:    bsdttyopen
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_BSDSerialPort_bsdttyopen
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
