all:
	jikes IanDarwin.java
	javadoc IanDarwin.java
	konqueror IanDarwin.html
clean:
	rm allclasses-frame.html
	rm deprecated-list.html
	rm help-doc.html
	rm index-all.html
	rm index.html
	rm overview-tree.html
	rm package-list
	rm packages.html
	rm serialized-form.html
	rm stylesheet.css
