
package jaxwsclient;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "CalcService", targetNamespace = "http://toy.service/", wsdlLocation = "http://localhost:7094/calc?wsdl")
public class CalcService
    extends Service
{

    private final static URL CALCSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(jaxwsclient.CalcService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = jaxwsclient.CalcService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:7094/calc?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7094/calc?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        CALCSERVICE_WSDL_LOCATION = url;
    }

    public CalcService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalcService() {
        super(CALCSERVICE_WSDL_LOCATION, new QName("http://toy.service/", "CalcService"));
    }

    /**
     * 
     * @return
     *     returns Calc
     */
    @WebEndpoint(name = "CalcPort")
    public Calc getCalcPort() {
        return super.getPort(new QName("http://toy.service/", "CalcPort"), Calc.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Calc
     */
    @WebEndpoint(name = "CalcPort")
    public Calc getCalcPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://toy.service/", "CalcPort"), Calc.class, features);
    }

}
